# Generated by Django 6.1 on 2026-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='working_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='working_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
