# Generated by Django 6.1 on 2026-08-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dentis',
            new_name='dentist',
        ),
    ]
